language: python
python:
  - "3.7"
before_install:
  - pip install --upgrade pip coverage codecov
  - pip install -r requirements.txt
install:
  - pip install .
script:
  - cd tests && coverage run --source=../maptool -m unittest -v && cd .. && coverage report
after_success:
  - codecov
